-- Webcam overlay: a pinned bubble in the top-right corner.
hl.window_rule({
    name = "webcam_overlay",
    match = { title = "^(WebcamOverlay)$" },
    float = true,
    pin = true,
    move = { "monitor_w-window_w-20", 20 },
    size = { 320, 320 },
    rounding = 20,
    border_size = 2,
})

-- Window classes generated by prism-tui.
hl.window_rule({
    name = "prism_tui",
    match = { class = "^(org.prism.)(impala|bluetui|lazygit|prism-api-test|prism-font|prism-update|prism-delete|prism-install|prism-install-webapp|prism-uninstall-webapp)$" },
    stay_focused = true,
    float = true,
    center = true,
    dim_around = true,
    size = { 900, 600 },
    rounding = 15,
})

hl.window_rule({
    name = "picture_in_picture",
    match = { title = "^(Picture-in-Picture)$" },
    float = true,
    pin = true,
    move = { "monitor_w-window_w-20", "monitor_h-window_h-20" },
    rounding = 10,
})

hl.window_rule({
    name = "yazi",
    match = { class = "^(org.prism.yazi)$" },
    stay_focused = false,
    float = false,
    center = false,
    dim_around = false,
    pin = false,
})

-- Common dialogs.
hl.window_rule({ match = { class = "^(xdg-desktop-portal-gtk)$" }, float = true })
hl.window_rule({ match = { class = "^(lxappearance)$" }, float = true, center = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, float = true, center = true, size = { 800, 500 } })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true, center = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, float = true, center = true })

hl.layer_rule({ match = { namespace = ".*" }, blur = true })

-- Dedicated music, chat, and AI workspaces.
hl.window_rule({ match = { title = "^(Spotify.*|YouTube Music|Apple Music|SoundCloud|Deezer.*)$" }, workspace = "99 silent" })
hl.window_rule({ match = { title = "^(WhatsApp.*|Telegram.*|Discord.*|Slack.*)$" }, workspace = "98 silent" })
hl.window_rule({ match = { title = "^(ChatGPT.*|Gemini.*|Claude.*|DeepSeek.*)$" }, workspace = "97 silent" })
